name: Ruff Check

on:
  push:


jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Ruff and lint
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"